apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-staging
 namespace: cert-manager
spec:
 acme:
   # The ACME server URL
   # This ClusterIssuer is named letsencrypt-staging because it uses the Let's encrypt STAGING server
   # This is because the production server rate-limits requests made against it, so for testing purposes
   # we want to use the staging server. For production, we use the production server.
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: tuuli.pollanen@gmail.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: letsencrypt-staging
   # Enable the HTTP-01 challenge provider
   solvers:
   - http01:
       ingress:
         class:  nginx
