namespace: staging
commonLabels:
  environment: staging
resources:
- ../../base
- ingress.yaml
- namespace.yaml
- sealed-secret.yaml
configMapGenerator:
- envs:
  - .env.config
  name: getting-started
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: tuuli/getting-started
  newTag: ece40b2
