namespace: production
commonLabels:
  environment: production
resources:
- ../../base
- ingress.yaml
configMapGenerator:
- envs:
  - .env.config
  name: getting-started
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: getting-started/getting-started
  newTag: bf65614
- name: tuuli/getting-started
  newTag: b6e3580
